### ISSUE TITLE
Mismatch in time of a post 

### ISSUE THREAD

**Issue by ManaliTanna** [gcivil-nyu-org/INET-Monday-Fall2023-Team-2#155] opened 2023-11-16 21:45 UTC
I created a draft post at 4:37 PM from the create post tab. Then I navigated to my profile and checked on the post, and it said "published" at 9:37 PM over there. Probably a timezone mismatch. 

<img width="1512" alt="image" src="https://github.com/gcivil-nyu-org/INET-Monday-Fall2023-Team-1/assets/57152208/4d31356a-a287-46de-bcc5-00d6c346fdb5">

**Comment by ManaliTanna** [comment] 2023-11-16 21:47
Same thing happens for active posts and archived posts as well

**Comment by agoluoglu** [comment] 2023-11-17 21:53
Hi @ManaliTanna, I am closing this issue because this is not a bug. This is intentional. When you edit something, it does not change the original publication date. Think of other apps like Instagram; editing a caption doesn't alter the displayed date of when the post was originally published.

**Closed by agoluoglu** 2023-11-17 21:53 UTC
