### ISSUE TITLE
UI issue: The color of the text in the profile is a bit hard to read

### ISSUE THREAD

**Issue by ManaliTanna** [gcivil-nyu-org/INET-Monday-Fall2023-Team-2#154] opened 2023-11-16 21:36 UTC
In the user's profile, the color of the text "Change Password" and "Delete Account" is a bit hard to read.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDNpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--557253a8348260e863e636d83952fd4c4705b9a6/image.png)

**Comment by agoluoglu** [comment] 2023-11-17 21:51
Hi @ManaliTanna , I am closing this issue because this is not a bug. The UI design is not a top priority (compared to implementing features), so most of our UI is temporary placeholder text. At the end we will make the app "prettier" when it is more fully functional.

**Closed by agoluoglu** 2023-11-17 21:51 UTC
